config/routes.rb
Music::Application.routes.draw do
  resources :artists

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :name, :band_id
  belongs_to :band

  has_many :authored_songs,
  					class_name: 'Song',
  					foreign_key: 'author_id'

  has_many :performed_songs, through: :band, source: :recordings

  def self.songs_per_artist
  	total = self
  		.select("artists.name AS artist, songs.name AS song")
  		.joins(:authored_songs)
  		.group('artists.id, songs.id')

  	total.inject({}) do |memo, object|
  		memo[object.artist] ||= []
  		memo[object.artist] << object.song
  		memo
  	end
  end
end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :name
  has_many :artists
  has_many :recordings
  has_many :songs, through: :recordings

  def self.recorded_song_repeatedly
		self
			.select('bands.*,
							s.name AS song_name,
							COUNT(r.band_id) AS song_count')
			.having('song_count > 1')
			.joins("INNER JOIN recordings r ON r.band_id = bands.id")
			.joins("INNER JOIN songs s ON r.song_id = s.id")
			.group('bands.id, s.name')
  end
end

app/models/recording.rb
class Recording < ActiveRecord::Base
  attr_accessible :band_id, :song_id

  belongs_to :band
  belongs_to :song
end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :name, :author_id

  belongs_to :artist, foreign_key: 'author_id'
  has_many :recordings
  has_many :bands, through: :recordings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def show
    @artist = Artist.find(params[:id])
  end

  def index
    @artists = Artist.all
  end

  def new
  end

  def destroy
  end

  def edit
  end

  def update
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
  def format_link_title(artist)
    if artist.band
      "#{artist.name} - <i>#{artist.band.name}</i>".html_safe
    else
      "#{artist.name}"
    end
  end
end

app/views/artists/create.html.erb
<h1>Artists#create</h1>
<p>Find me in app/views/artists/create.html.erb</p>

app/views/artists/destroy.html.erb
<h1>Artists#destroy</h1>
<p>Find me in app/views/artists/destroy.html.erb</p>

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<h1>Hit Artists of the Day . 5</h1>

<ul>
  <% @artists.each do |artist| %>
  <li>
    <%= link_to format_link_title(artist), artist_path(artist) %>
    </li>
  <% end %>
</ul>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<h2><i><%= @artist.band.name if @artist.band %></i></h2>
<h4><b>Songs:</b></h4>
<ul>
  <% @artist.authored_songs.each do |song| %>
    <li>
      <%= song.name %>
    </li>
  <% end %>
</ul>

app/views/artists/update.html.erb
<h1>Artists#update</h1>
<p>Find me in app/views/artists/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Music</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>